name: testnet

services:
  goat-relayer:
    image: goatnetwork/goat-relayer:latest
    depends_on:
      goat-relayer-1:
        condition: service_started
    env_file:
      - .env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.12/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
      - RELAYER_PRIVATE_KEY=522afed335d0e13e644ef35a4bac3d4e745a707ad258fd3a87e4bfa03c3d470c
      - RELAYER_BLS_SK=680e85e4eac1a3e4f54b6535e35c7e5308a483859b1c2fe2e0a1c04e777c38b0
    ports:
      - "8080:8080"
      - "50051:50051"
      - "4001:4001"
    volumes:
      - /data/db:/app/db
 