name: testnet

services:
  goat-relayer:
    image: goatnetwork/goat-relayer:latest
    env_file:
      - .env
    environment:
      - LIBP2P_BOOT_NODES=/ip4/172.31.32.12/tcp/4001/p2p/12D3KooWEyrTn9ZD2Kidma4EKZ7ajaa7XDdje822WNZBRxpwQBYx
    ports:
      - "8080:8080"
      - "50051:50051"
      - "4001:4001"
    volumes:
      - /data/db:/app/db
 