name: testnet3

services:
  geth:
    image: ghcr.io/goatnetwork/goat-geth:v0.1.0
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 30s
    command:
      - --goat=testnet3
      - --goat.preset=bootnode,rpc
      # open it if you need an archive node
      # - --gcmode=archive
    volumes:
      - /data/geth:/root/.ethereum
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 50m

  goat:
    image: ghcr.io/goatnetwork/goat:v0.1.1
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 30s
    command:
      - start
      - --goat.geth=/geth/geth.ipc
      - --goat.preset=bootnode,rpc
      - --chain-id=goat-testnet3
    depends_on:
      - geth
    volumes:
      - /data/goat:/root/.goat
      - /data/geth:/geth
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 50m