- name: Bridge Api setup and run
  hosts: bridge_api_servers
  become: true
  gather_facts: false
  vars:
    cleanup: false # default not cleanup
  tasks:
    # Bridge Api setup
    - name: Clean up Bridge Api environment
      when: cleanup | bool
      block:
        - name: Stop and delete Docker containers
          ansible.builtin.shell: |
            docker compose down -v
          args:
            chdir: /data/runtime/
          ignore_errors: yes

        - name: Delete runtime directory
          ansible.builtin.file:
            path: "/data/runtime"
            state: absent

        - name: Delete Bridge Api directory
          ansible.builtin.file:
            path: "/data/app"
            state: absent

    - name: Create runtime directory
      ansible.builtin.file:
        path: "/data/runtime"
        state: directory
        mode: '0755'

    - name: Copy docker-compose files
      changed_when: false
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/data/runtime/{{ item.path }}"
        mode: "{{ item.mode }}"
      with_filetree:
        - "files/front/bridge_api/"
      when: item.state == 'file'

    - name: Start Bridge Api
      ansible.builtin.shell: |
        docker compose up -d
      args:
        chdir: /data/runtime/
