- name: Validator setup and run
  hosts: rpc_servers
  become: true
  gather_facts: false
  vars:
    cleanup: false  # default not cleanup
    validator_files: # length should equal to the number of validators
      - "secrets/goat/validator/priv_validator_key_1.json"
      - "secrets/goat/validator/priv_validator_key_2.json"
      - "secrets/goat/validator/priv_validator_key_3.json"
  tasks:
    - name: Clean up Goat environment
      when: cleanup | bool
      block:
        - name: Stop and delete Docker containers
          ansible.builtin.shell: |
            docker compose down -v
          args:
            chdir: /data/runtime/
          ignore_errors: yes

        - name: Delete runtime directory
          ansible.builtin.file:
            path: "/data/runtime"
            state: absent

        - name: Delete geth directory
          ansible.builtin.file:
            path: "/data/geth"
            state: absent

        - name: Delete goat directory
          ansible.builtin.file:
            path: "/data/goat"
            state: absent

    - name: Create target directory
      ansible.builtin.file:
        path: "/data/runtime"
        state: directory
        mode: '0755'

    - name: Create genesis subdirectory
      ansible.builtin.file:
        path: "/data/runtime/genesis"
        state: directory
        mode: '0755'

    - name: Copy docker-compose and genesis files
      changed_when: false
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/data/runtime/{{ item.path }}"
        mode: "{{ item.mode }}"
      with_filetree:
        - "files/goat/"
      when: item.state == 'file'

    - name: Init goat
      ansible.builtin.shell: |
        docker compose -f docker-compose-init.yml up
      args:
        chdir: /data/runtime/

    - name: Copy validator files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/data/goat/config/priv_validator_key.json"
        mode: '0644'
      loop: "{{ validator_files }}"
      loop_control:
        index_var: idx
      when: idx == ansible_play_hosts.index(inventory_hostname)

    - name: Start goat
      ansible.builtin.shell: |
        docker compose up -d
      args:
        chdir: /data/runtime/
