- name: Bootnode setup and run
  hosts: goat_bootnode_servers
  become: true
  gather_facts: false
  vars:
    cleanup: false # default not cleanup
    geth_nodekey_file: secrets/goat/bootnode/geth_nodekey.key
    goat_nodekey_file: secrets/goat/bootnode/goat_nodekey.json
    validator_files: # length should equal to the number of validators
      - "secrets/goat/bootnode/priv_validator_key_0.json"
  tasks:
    # Goat setup
    - name: Clean up Goat environment
      when: cleanup | bool
      block:
        - name: Stop and delete Docker containers
          ansible.builtin.shell: |
            docker compose down -v
          args:
            chdir: /data/runtime/
          ignore_errors: yes

        - name: Delete runtime directory
          ansible.builtin.file:
            path: "/data/runtime"
            state: absent

        - name: Delete geth directory
          ansible.builtin.file:
            path: "/data/geth"
            state: absent

        - name: Delete goat directory
          ansible.builtin.file:
            path: "/data/goat"
            state: absent

    - name: Create target directory
      ansible.builtin.file:
        path: "/data/runtime"
        state: directory
        mode: '0755'

    - name: Create genesis subdirectory
      ansible.builtin.file:
        path: "/data/runtime/genesis"
        state: directory
        mode: '0755'

    - name: Copy docker-compose and genesis files
      changed_when: false
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/data/runtime/{{ item.path }}"
        mode: "{{ item.mode }}"
      with_filetree:
        - "files/goat/"
      when: item.state == 'file'

    - name: Init Goat CL & EL
      when: cleanup | bool
      ansible.builtin.shell: |
        docker compose -f docker-compose-init.yml up
      args:
        chdir: /data/runtime/

    - name: Copy Geth nodekey file
      ansible.builtin.copy:
        src: "{{ geth_nodekey_file }}"
        dest: /data/geth/geth/nodekey
        mode: '0644'

    - name: Copy Goat nodekey file
      ansible.builtin.copy:
        src: "{{ goat_nodekey_file }}"
        dest: /data/goat/config/node_key.json
        mode: '0644'

    - name: Copy Goat validator key files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/data/goat/config/priv_validator_key.json"
        mode: '0644'
      loop: "{{ validator_files }}"
      loop_control:
        index_var: idx
      when: idx == ansible_play_hosts.index(inventory_hostname)

    - name: Start Goat CL & EL
      ansible.builtin.shell: |
        docker compose up -d --force-recreate
      args:
        chdir: /data/runtime/
