- name: Voter setup and run
  hosts: relayer_voter_servers
  become: true
  gather_facts: false
  vars:
    cleanup: false # default not cleanup
    voter_env_files:
      - "secrets/relayer/voter/voter_b.env"
      - "secrets/relayer/voter/voter_c.env"
  tasks:
    # Relayer setup
    - name: Clean up Relayer environment
      when: cleanup | bool
      block:
        - name: Stop and delete Docker containers
          ansible.builtin.shell: |
            docker compose down -v
          args:
            chdir: /data/runtime/
          ignore_errors: yes

        - name: Delete runtime directory
          ansible.builtin.file:
            path: "/data/runtime"
            state: absent

        - name: Delete db directory
          ansible.builtin.file:
            path: "/data/db"
            state: absent

    - name: Create runtime directory
      ansible.builtin.file:
        path: "/data/runtime"
        state: directory
        mode: '0755'

    - name: Create db directory
      ansible.builtin.file:
        path: "/data/db"
        state: directory
        mode: '0755'

    - name: Copy docker-compose files
      changed_when: false
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/data/runtime/{{ item.path }}"
        mode: "{{ item.mode }}"
      with_filetree:
        - "files/relayer/"
      when: item.state == 'file'

    - name: Copy voter env files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/data/runtime/.env"
        mode: '0644'
      loop: "{{ voter_env_files }}"
      loop_control:
        index_var: idx
      when: idx == ansible_play_hosts.index(inventory_hostname)

    - name: Start relayer
      ansible.builtin.shell: |
        docker compose up -d --force-recreate
      args:
        chdir: /data/runtime/
